### ISSUE TITLE
Support ignore comments

### ISSUE THREAD

**Issue by dmajda** [openSUSE/scanny#1]
We should support ignore comments like the original Thomas's scanner does. I've always found the original scanner comments somewhat unparseable, so I propose the following comment types:

```
# SCANNY_IGNORE        - ignores this line
# SCANNY_IGNORE_NEXT   - ignores next line
# SCANNY_IGNORE_NEXT_n - ignores next n lines
```

**Comment by ghost** [comment]
Am Freitag, 29. Juli 2011, 15:45:53 schrieb dmajda:

> We should support ignore comments like the original Thomas's scanner does. I've always found the original scanner comments somewhat unparseable, so I propose the following comment types:
> 
> ```
> # SCANNY_IGNORE        - ignores this line
> # SCANNY_IGNORE_NEXT   - ignores next line
> # SCANNY_IGNORE_NEXT_n - ignores next n lines
> ```

Sounds good.

Bye
Thomas 

## 

Thomas Biege thomas@suse.de, SUSE LINUX, Security Support & Auditing

## SUSE LINUX GmbH, GF: Jeff Hawn, Jennifer Guild, Felix Imendörffer, HRB 21284 (AG Nürnberg

  Wer aufhoert besser werden zu wollen, hoert auf gut zu sein.
                            -- Marie von Ebner-Eschenbach
