### ISSUE TITLE
Investigate Jenkins integration

### ISSUE THREAD

**Issue by dmajda** [openSUSE/scanny#3]
Since we will probably want to run the scanner as part of our CI, we should look into what is necessary to run it in Jenkins and adapt the scanner as necessary.

**Comment by ghost** [comment]
Am Freitag, 29. Juli 2011, 15:56:49 schrieb dmajda:

> Since we will probably want to run the scanner as part of our CI, we should look into what is necessary to run it in Jenkins and adapt the scanner as necessary.

Hi,
what is Jenkins?

Cheerio,
Thomas

## 

Thomas Biege thomas@suse.de, SUSE LINUX, Security Support & Auditing

## SUSE LINUX GmbH, GF: Jeff Hawn, Jennifer Guild, Felix Imendörffer, HRB 21284 (AG Nürnberg

  Wer aufhoert besser werden zu wollen, hoert auf gut zu sein.
                            -- Marie von Ebner-Eschenbach

**Comment by flavio** [comment]
Thomas said

> what is Jenkins?

Jenkins is the continuous integration server we use to test our ruby code.

**Comment by flavio** [comment]
Implemented with 5b4a4a05731cdd5628ec7aedb267744c00f3c27b
