### ISSUE TITLE
Do we need the Rake task?

### ISSUE THREAD

**Issue by dmajda** [openSUSE/scanny#4]
I am not sure that we need to have the Rake task. I origianlly copied it from Roodi, but currently we don't need it for anything and it became out-of-sync with code in `/bin/scanny`.

Flavio, what do you think? If you're not sure as well, I'd vote for ditching it (it can be restored again easily if needed).

**Comment by flavio** [comment]
I agree with you, we can get rid of it.

**Comment by dmajda** [comment]
OK, I [deleted it](https://github.com/openSUSE/scanny/commit/3ebed058d2cc73de25f458989e17e5343eb15c6c).
